# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 20:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('emailaddress', models.CharField(max_length=255, validators=[django.core.validators.EmailValidator()])),
                ('completedOn', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completedOn', models.DateTimeField()),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchenge_transition.Steps')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchenge_transition.Users')),
            ],
        ),
    ]
