# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchenge_transition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
