# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchenge_transition', '0002_users_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='steps',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='users',
            name='emailaddress',
        ),
        migrations.AddField(
            model_name='users',
            name='alias',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='comments',
            field=models.TextField(default='** Enter Relevent notes here **'),
        ),
        migrations.AddField(
            model_name='users',
            name='completedBy',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
