# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-10 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_transition', '0002_auto_20170210_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstep',
            name='completedBy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
