# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('alias', models.CharField(max_length=100, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completedOn', models.DateTimeField(null=True)),
                ('completedBy', models.CharField(max_length=200, null=True)),
                ('comments', models.TextField(default='** Enter Relevent notes here **')),
            ],
        ),
        migrations.CreateModel(
            name='UserStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completedOn', models.DateTimeField()),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange_transition.Step')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange_transition.User')),
            ],
        ),
    ]
