# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_tracker', '0003_userstep_completedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstep',
            name='completedOn',
            field=models.DateTimeField(null=True),
        ),
    ]
