# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_transition', '0004_auto_20170221_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
