# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_tracker', '0005_auto_20170222_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='optional',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='alias',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
